-- ── On-demand mnemonics ───────────────────────────────────────────────────
-- An optional memory device per flashcard, generated by the AI on request and
-- then stored (editable, regeneratable) rather than re-generated every view.
-- RLS on `flashcards` already covers it.

alter table public.flashcards
  add column mnemonic text;

comment on column public.flashcards.mnemonic is
  'AI-generated (or user-edited) memory device; null until requested.';
